import type { BackupEnvelope } from "@/lib/backup";
import type { CashFlowBackupTables } from "./index";

/** Complete JSON fixture shared by pure validation and IndexedDB roundtrip tests. */
export function cashFlowBackupFixture(): CashFlowBackupTables {
  const payable = {
    id: "invoice-a",
    clientId: "company-a",
    source: "contifico" as const,
    supplier: "Proveedor á",
    supplierTaxId: "1790000010001",
    docType: "FAC",
    docNumber: "001-002-123",
    description: "Factura original",
    issuedOn: "2026-01-01",
    dueOn: "2026-02-01",
    amount: 123.45,
    withholdings: 3.45,
    payments: 20,
    balance: 100,
    centerName: "HA",
    priority: "urgent" as const,
    cash: true,
    payOn: "2026-10-09",
    payFromAccountId: "account-a",
    observation: "Revisar crédito",
    approved: 0,
    finalReview: true,
    notified: false,
    status: "open" as const,
    settledOn: null,
    cutDate: "2026-10-08",
  };
  return {
    clients: [
      {
        id: "company-a",
        name: "Empresa á",
        logo: {
          dataUrl:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=",
          mime: "image/png",
          width: 1,
          height: 1,
        },
        letterhead: { name: "Empresa á S.A.", lines: ["RUC 1790000010001", "Quito · 02 1234567"] },
      },
      {
        id: "company-b",
        name: "Empresa B",
        letterhead: { name: "Empresa B", lines: [] },
        logo: {
          // One pixel encoded as JPEG, with optional APP metadata removed.
          dataUrl:
            "data:image/jpeg;base64,/9j/wAALCAABAAEBAREA/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9sAQwACAgICAgIDAgIDBQMDAwUGBQUFBQYIBgYGBgYICggICAgICAoKCgoKCgoKDAwMDAwMDg4ODg4PDw8PDw8PDw8P/90ABAAB/9oACAEBAAA/AP38r//Z",
          mime: "image/jpeg",
          width: 1,
          height: 1,
        },
      },
    ],
    centers: [
      { id: "center-a", clientId: "company-a", name: "HA" },
      { id: "center-b", clientId: "company-b", name: "Sucursal B" },
    ],
    accounts: [
      {
        id: "account-a",
        clientId: "company-a",
        bank: "Pichincha",
        number: "000123",
        label: "Cuenta HA",
        overdraft: 0,
        overdraftStartsOn: "2026-01-01",
        overdraftEndsOn: null,
        centerId: "center-a",
        checkLayout: {
          format: "pichincha",
          width: 297,
          height: 210,
          fontSize: 10,
          city: "Quito",
          offsetX: -1.5,
          offsetY: 0,
          amount: { x: 12, y: 24, width: 40 },
          payee: { x: 10, y: 30, width: 120 },
          words: { x: 10, y: 40, width: 150 },
          place: { x: 10, y: 50, width: 100 },
          filler: { x: 10, y: 45, width: 100 },
        },
      },
      {
        id: "account-b",
        clientId: "company-b",
        bank: "Produbanco",
        number: "000456",
        overdraft: 500.25,
        overdraftStartsOn: null,
        overdraftEndsOn: "2026-12-31",
        centerId: null,
      },
    ],
    payables: [
      payable,
      {
        ...payable,
        id: "invoice-b",
        clientId: "company-b",
        source: "dingoo",
        centerName: null,
        payFromAccountId: null,
        priority: null,
        cash: false,
        approved: null,
        status: "settled",
        settledOn: "2026-09-01",
        balance: 0,
      },
    ],
    manualObligations: [
      {
        ...payable,
        id: "manual-a",
        source: "manual",
        kind: "arriendo",
        supplierTaxId: null,
        issuedOn: null,
        dueOn: null,
      },
      {
        ...payable,
        id: "manual-b",
        clientId: "company-b",
        source: "manual",
        kind: "Servicios básicos",
        priority: null,
        status: "settled",
        settledOn: "2026-10-07",
        payFromAccountId: "account-b",
        approved: null,
        cash: false,
      },
    ],
    checks: [
      {
        id: "check-a",
        clientId: "company-a",
        voucher: "0001",
        bank: "Pichincha",
        accountId: "account-a",
        payee: "Proveedor á",
        number: "001",
        amount: 50.25,
        issuedOn: "2026-09-01",
        step: "delivered",
        voided: false,
        cashedOn: null,
        expectedCashOn: "2026-10-10",
        flowLinkedOn: "2026-10-08",
        flowPriority: "pending",
        flowApproved: 0,
        flowPayOn: null,
        flowPayFromAccountId: "account-a",
        place: "Quito",
        note: "Nota conservada",
        payeeTaxId: "0101010101",
        payeeAddress: "Calle Uno",
        payments: [
          {
            payableId: "invoice-a",
            docNumber: "001-002-123",
            issuedOn: "2026-01-01",
            balance: 100,
            amount: 30.25,
          },
          {
            payableId: "deleted-invoice",
            docNumber: "histórico",
            issuedOn: null,
            balance: 20,
            amount: 20,
          },
        ],
      },
      {
        id: "check-b",
        clientId: "company-b",
        voucher: "0002",
        bank: "Produbanco",
        accountId: null,
        payee: "Proveedor B",
        number: "002",
        amount: 0,
        issuedOn: null,
        step: "cashed",
        voided: true,
        cashedOn: "2026-09-15",
        expectedCashOn: null,
        flowLinkedOn: null,
        flowApproved: null,
        flowPayFromAccountId: null,
        place: "Guayaquil",
        note: "Anulado",
        payments: [],
      },
    ],
    flows: [
      {
        id: "flow-a-previous",
        clientId: "company-a",
        date: "2026-09-01",
        balances: { "account-a": 0, "deleted-account": -50.75 },
        incomes: [
          { id: "income-a", concept: "Reservas", amount: 10.25, accountId: "deleted-account" },
        ],
        notes: { "balance:account-a": "Saldo previo", "income:income-a": "Por cobrar" },
      },
      {
        id: "flow-a",
        clientId: "company-a",
        date: "2026-10-08",
        balances: { "account-a": 100.25 },
        incomes: [{ id: "income-today", concept: "Venta", amount: 0, accountId: null }],
        notes: {},
      },
      {
        id: "flow-b",
        clientId: "company-b",
        date: "2026-10-08",
        balances: { "account-b": -10 },
        incomes: [],
      },
    ],
    cashEntries: [
      {
        id: "cash-a",
        clientId: "company-a",
        section: "initial",
        date: "2026-09-01",
        detail: "Movimiento inicial",
        amounts: { "center-a": 0, "deleted-center": 12.25 },
        loan: { fromCenterId: "center-a", toCenterId: "deleted-center", amount: 0 },
        observation: "Histórico",
      },
      {
        id: "cash-b",
        clientId: "company-b",
        section: "misc",
        date: "2026-10-08",
        detail: "Varios",
        amounts: { "": -12.25 },
        loan: null,
        observation: "Caja sin centro",
      },
    ],
    meta: [
      {
        key: "company-a::contifico",
        clientId: "company-a",
        source: "contifico",
        cutDate: "2026-10-08",
        companyName: "Empresa á S.A.",
        loadedAt: "2026-10-08T14:15:16.123Z",
      },
      {
        key: "company-b::dingoo",
        clientId: "company-b",
        source: "dingoo",
        cutDate: "2026-10-07",
        companyName: null,
        loadedAt: "2026-10-07T14:15:16.000Z",
      },
    ],
    active: [{ key: "active", clientId: "company-b" }],
  };
}

export function cashFlowBackupEnvelopeFixture(): BackupEnvelope<CashFlowBackupTables> {
  return {
    format: "liderboard-backup",
    formatVersion: 1,
    module: "cash-flow",
    dataVersion: 1,
    databaseVersion: 5,
    createdAt: "2026-10-08T14:15:16.123Z",
    tables: cashFlowBackupFixture(),
  };
}
