/**
 * Los SEIS empleados del rol de MARZO 2026 de HOTEL BOUTIQUE CULTURA MANOR, con lo que el
 * archivo del contador declara como entrada y lo que sus propias fórmulas calculan.
 *
 * Es el fixture de oro del motor: `golden.test.ts` exige que `computeEmployeePayroll` reproduzca
 * las 20 columnas derivadas de los seis **exactas al bit**, ruido de coma flotante incluido
 * (`569.5500000000001`, `457.69000000000005`, `81.00999999999999`). Ese ruido no es un defecto
 * del fixture: los totales del libro no se redondean (§9), y reproducirlo es lo que hace que la
 * app y el Excel digan la misma cifra.
 *
 * Extraído leyendo el `.xls` real, pero copiado aquí como dato ESTÁTICO: el archivo vive en
 * `.context/` y está fuera de git, así que ningún test puede depender de él —la misma regla que
 * `upload/rol-general.fixtures.ts` ya sigue.
 *
 * El `approvedOvertime` de cada fila no está transcrito a mano: se DEDUCE de los propios valores
 * del archivo —si `M` ≠ `J+K+L`, `M` es el importe que se reconoció; si coinciden, no hubo
 * recorte y va `null`—, que es también como lo recuperará el importador sin leer fórmulas.
 */
import type { ExtraIncomeTotals, PayrollEmployeeComputation, PayrollEmployeeInput } from "./types";

/**
 * El libro de Cultura Manor no declara ningún concepto de ingreso extra: sus trece ingresos son los
 * del catálogo. Va explícito en las seis filas —y no como un default del tipo— porque es
 * justamente lo que este fixture certifica: **con los dos agregados en cero, las veinte columnas
 * son las del archivo, al bit.**
 */
const NO_EXTRAS: ExtraIncomeTotals = { contributory: 0, nonContributory: 0 };

export interface GoldenEmployee {
  /** Fila de la hoja `GENERAL`, para poder volver al archivo. */
  row: number;
  name: string;
  input: PayrollEmployeeInput;
  expected: PayrollEmployeeComputation;
}

export const GOLDEN_MARCH_2026: readonly GoldenEmployee[] = [
  {
    // `M15` trae `*0`: sus 5,5 horas al 50 % valen 16,75 y no se reconoció ninguna.
    row: 15,
    name: "MORALES MENA SILVIA JIMENA",
    input: {
      baseSalary: 487.21,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: true,
      overtimeHours50: 5.5,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: 0,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 64.25,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 457.69,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 487.21,
      overtimePay50: 16.75,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.6,
      reserveFundPaid: 0,
      grossIncome: 567.98,
      iessEmployee: 46.04,
      totalDeductions: 110.28999999999999,
      netPay: 457.69000000000005,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.2,
      vacationProvision: 21.97,
      reserveFundAccrued: 0,
      totalProvision: 81.17,
      employerCost: 649.15,
      difference: 0,
    },
  },
  {
    // `L16` trae `*0` y usa 0,15 en vez de 0,25 (errata §11.2), así que su entrada EFECTIVA de
    // horas de la tercera clase es CERO aunque la celda `I16` diga 140. Su `M` sí suma, pero
    // no hay nada que sumar. Es la única con diferencia contra lo pagado: −41,71.
    row: 16,
    name: "VEGA GARCIA MARIANA DE JESUS",
    input: {
      baseSalary: 482.04,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 0,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: null,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 558.54,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 482.04,
      overtimePay50: 0,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.17,
      reserveFundPaid: 0,
      grossIncome: 562.38,
      iessEmployee: 45.55,
      totalDeductions: 45.55,
      netPay: 516.83,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 58.57,
      vacationProvision: 21.76,
      reserveFundAccrued: 0,
      totalProvision: 80.33,
      employerCost: 642.71,
      difference: -41.70999999999992,
    },
  },
  {
    // `M28` trae `*0`: 26 horas al 50 % por 79,41 que no se reconocieron.
    row: 28,
    name: "SANDOVAL COLIMBA PEDRO MANUEL",
    input: {
      baseSalary: 488.66,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 26,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: 0,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 523.37,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 488.66,
      overtimePay50: 79.41,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.72,
      reserveFundPaid: 0,
      grossIncome: 569.5500000000001,
      iessEmployee: 46.18,
      totalDeductions: 46.18,
      netPay: 523.3700000000001,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.37,
      vacationProvision: 22.03,
      reserveFundAccrued: 0,
      totalProvision: 81.4,
      employerCost: 650.95,
      difference: 0,
    },
  },
  {
    // `M29` trae `*0`: 13 horas al 50 % por 39,51 que no se reconocieron.
    row: 29,
    name: "ACOSTA MARIA PASTORA",
    input: {
      baseSalary: 486.25,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 13,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: 0,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 520.99,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 486.25,
      overtimePay50: 39.51,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.52,
      reserveFundPaid: 0,
      grossIncome: 566.9399999999999,
      iessEmployee: 45.95,
      totalDeductions: 45.95,
      netPay: 520.9899999999999,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.08,
      vacationProvision: 21.93,
      reserveFundAccrued: 0,
      totalProvision: 81.00999999999999,
      employerCost: 647.9499999999999,
      difference: 0,
    },
  },
  {
    // Sin horas extras, y por eso su fórmula de `M` sigue sana.
    row: 35,
    name: "SANDOVAL ACOSTA LUIS FERNANDO",
    input: {
      baseSalary: 487.21,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 0,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: null,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 521.94,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 487.21,
      overtimePay50: 0,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.6,
      reserveFundPaid: 0,
      grossIncome: 567.98,
      iessEmployee: 46.04,
      totalDeductions: 46.04,
      netPay: 521.94,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.2,
      vacationProvision: 21.97,
      reserveFundAccrued: 0,
      totalProvision: 81.17,
      employerCost: 649.15,
      difference: 0,
    },
  },
  {
    // Sin horas extras. Tiene 200 de anticipo de sueldo (`AA36`), que es lo que baja su líquido.
    row: 36,
    name: "SORIA CHALA MISHELL FERNANDA",
    input: {
      baseSalary: 487.21,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 0,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: null,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 200,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 321.94,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 487.21,
      overtimePay50: 0,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.6,
      reserveFundPaid: 0,
      grossIncome: 567.98,
      iessEmployee: 46.04,
      totalDeductions: 246.04,
      netPay: 321.94000000000005,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.2,
      vacationProvision: 21.97,
      reserveFundAccrued: 0,
      totalProvision: 81.17,
      employerCost: 649.15,
      difference: 0,
    },
  },
];
