/**
 * The SIX employees of the MARCH 2026 rol of HOTEL BOUTIQUE CULTURA MANOR, with what the
 * accountant's file declares as input and what its own formulas compute.
 *
 * It is the engine's golden fixture: `golden.test.ts` requires `computeEmployeePayroll` to reproduce
 * the 20 derived columns of all six **exact to the bit**, floating-point noise included
 * (`569.5500000000001`, `457.69000000000005`, `81.00999999999999`). That noise is not a defect of the
 * fixture: the book's totals are not rounded (§9), and reproducing it is what makes the app and the
 * Excel say the same figure.
 *
 * Extracted by reading the real `.xls`, but copied here as STATIC data: the file lives in `.context/`
 * and is outside git, so no test can depend on it —the same rule `upload/rol-general.fixtures.ts`
 * already follows.
 *
 * Each row's `approvedOvertime` is not transcribed by hand: it is DEDUCED from the file's own values
 * —if `M` ≠ `J+K+L`, `M` is the amount that was recognised; if they match, there was no trim and it
 * goes `null`—, which is also how the importer will recover it without reading formulas.
 */
import type { ExtraIncomeTotals, PayrollEmployeeComputation, PayrollEmployeeInput } from "./types";

/**
 * Cultura Manor's book declares no extra income concept: its thirteen income items are the
 * catalogue's. It goes explicit in all six rows —and not as a default of the type— because it is
 * precisely what this fixture certifies: **with both aggregates at zero, the twenty columns are the
 * file's, to the bit.**
 */
const NO_EXTRAS: ExtraIncomeTotals = { contributory: 0, nonContributory: 0 };

export interface GoldenEmployee {
  /** Row of the `GENERAL` sheet, so it is possible to go back to the file. */
  row: number;
  name: string;
  input: PayrollEmployeeInput;
  expected: PayrollEmployeeComputation;
}

export const GOLDEN_MARCH_2026: readonly GoldenEmployee[] = [
  {
    // `M15` carries `*0`: their 5.5 hours at 50 % are worth 16.75 and none was recognised.
    row: 15,
    name: "MORALES MENA SILVIA JIMENA",
    input: {
      baseSalary: 487.21,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: true,
      overtimeHours50: 5.5,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: 0,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 64.25,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 457.69,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 487.21,
      overtimePay50: 16.75,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.6,
      reserveFundPaid: 0,
      grossIncome: 567.98,
      iessEmployee: 46.04,
      totalDeductions: 110.28999999999999,
      netPay: 457.69000000000005,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.2,
      vacationProvision: 21.97,
      reserveFundAccrued: 0,
      totalProvision: 81.17,
      employerCost: 649.15,
      difference: 0,
    },
  },
  {
    // `L16` carries `*0` and uses 0.15 instead of 0.25 (typo §11.2), so their EFFECTIVE input of
    // third-class hours is ZERO even though cell `I16` says 140. Their `M` does add up, but there is
    // nothing to add. It is the only one with a difference against what was paid: −41.71.
    row: 16,
    name: "VEGA GARCIA MARIANA DE JESUS",
    input: {
      baseSalary: 482.04,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 0,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: null,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 558.54,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 482.04,
      overtimePay50: 0,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.17,
      reserveFundPaid: 0,
      grossIncome: 562.38,
      iessEmployee: 45.55,
      totalDeductions: 45.55,
      netPay: 516.83,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 58.57,
      vacationProvision: 21.76,
      reserveFundAccrued: 0,
      totalProvision: 80.33,
      employerCost: 642.71,
      difference: -41.70999999999992,
    },
  },
  {
    // `M28` carries `*0`: 26 hours at 50 % worth 79.41 that were not recognised.
    row: 28,
    name: "SANDOVAL COLIMBA PEDRO MANUEL",
    input: {
      baseSalary: 488.66,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 26,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: 0,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 523.37,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 488.66,
      overtimePay50: 79.41,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.72,
      reserveFundPaid: 0,
      grossIncome: 569.5500000000001,
      iessEmployee: 46.18,
      totalDeductions: 46.18,
      netPay: 523.3700000000001,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.37,
      vacationProvision: 22.03,
      reserveFundAccrued: 0,
      totalProvision: 81.4,
      employerCost: 650.95,
      difference: 0,
    },
  },
  {
    // `M29` carries `*0`: 13 hours at 50 % worth 39.51 that were not recognised.
    row: 29,
    name: "ACOSTA MARIA PASTORA",
    input: {
      baseSalary: 486.25,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 13,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: 0,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 520.99,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 486.25,
      overtimePay50: 39.51,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.52,
      reserveFundPaid: 0,
      grossIncome: 566.9399999999999,
      iessEmployee: 45.95,
      totalDeductions: 45.95,
      netPay: 520.9899999999999,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.08,
      vacationProvision: 21.93,
      reserveFundAccrued: 0,
      totalProvision: 81.00999999999999,
      employerCost: 647.9499999999999,
      difference: 0,
    },
  },
  {
    // No overtime, and that is why their `M` formula is still healthy.
    row: 35,
    name: "SANDOVAL ACOSTA LUIS FERNANDO",
    input: {
      baseSalary: 487.21,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 0,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: null,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 0,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 521.94,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 487.21,
      overtimePay50: 0,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.6,
      reserveFundPaid: 0,
      grossIncome: 567.98,
      iessEmployee: 46.04,
      totalDeductions: 46.04,
      netPay: 521.94,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.2,
      vacationProvision: 21.97,
      reserveFundAccrued: 0,
      totalProvision: 81.17,
      employerCost: 649.15,
      difference: 0,
    },
  },
  {
    // No overtime. They have 200 of a salary advance (`AA36`), which is what lowers their net pay.
    row: 36,
    name: "SORIA CHALA MISHELL FERNANDA",
    input: {
      baseSalary: 487.21,
      days: 30,
      contractType: "CT",
      hasReserveFund: false,
      accumulatesReserveFund: false,
      overtimeHours50: 0,
      overtimeHours100: 0,
      overtimeHours25: 0,
      approvedOvertime: null,
      vacationPay: 0,
      privateInsurance: 0,
      allowances: 0,
      fixedCommission: 0,
      variableCommission: 0,
      bonus: 0,
      extras: NO_EXTRAS,
      deductions: {
        iessLoans: 0,
        unpaidLeave: 0,
        salaryAdvance: 200,
        companyLoans: 0,
        incomeTax: 0,
        meals: 0,
        fines: 0,
        inHouseConsumption: 0,
        solidarityContribution: 0,
        otherDeductions: 0,
        partTimeDeduction: 0,
        medicalLeaveDeduction: 0,
      },
      paid: 321.94,
      flags: { provisionsThirteenth: false, provisionsFourteenth: false },
    },
    expected: {
      unifiedSalary: 487.21,
      overtimePay50: 0,
      overtimePay100: 0,
      overtimePay25: 0,
      overtimeTotal: 0,
      fourteenthMonthly: 40.17,
      thirteenthMonthly: 40.6,
      reserveFundPaid: 0,
      grossIncome: 567.98,
      iessEmployee: 46.04,
      totalDeductions: 246.04,
      netPay: 321.94000000000005,
      thirteenthProvision: 0,
      fourteenthProvision: 0,
      iessEmployer: 59.2,
      vacationProvision: 21.97,
      reserveFundAccrued: 0,
      totalProvision: 81.17,
      employerCost: 649.15,
      difference: 0,
    },
  },
];
